# Generated by Django 3.2.8 on 2021-10-24 17:42

import cats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_cat_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='cat_sex',
            new_name='cat_male',
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='cats.user', validators=[cats.models.limit_cats]),
        ),
    ]
